workflows:
  flutter-web-workflow:
    name: DeadTime Flutter Web Simple
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Create web directory
        script: |
          mkdir -p web
      - name: Create index.html
        script: |
          cat > web/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta content="IE=Edge" http-equiv="X-UA-Compatible">
            <meta name="description" content="DeadTime - AI-powered attention monetization platform">
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="black">
            <meta name="apple-mobile-web-app-title" content="DeadTime">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
            <title>DeadTime - Monetize Your Time</title>
            <style>
              body { margin: 0; background-color: #0F0F23; font-family: Arial, sans-serif; }
              .loading { 
                position: absolute; 
                top: 50%; 
                left: 50%; 
                transform: translate(-50%, -50%);
                color: #6C63FF;
                text-align: center;
              }
            </style>
          </head>
          <body>
            <div class="loading">
              <h1>⏰ DeadTime</h1>
              <p>Loading your money-making app...</p>
            </div>
            <script src="main.dart.js" type="application/javascript"></script>
          </body>
          </html>
          EOF
      - name: Create manifest.json
        script: |
          cat > web/manifest.json << 'EOF'
          {
            "name": "DeadTime - Monetize Your Time",
            "short_name": "DeadTime",
            "description": "AI-powered attention monetization platform",
            "start_url": "/",
            "display": "standalone",
            "background_color": "#0F0F23",
            "theme_color": "#6C63FF",
            "icons": [
              {
                "src": "favicon.png",
                "sizes": "192x192",
                "type": "image/png"
              }
            ]
          }
          EOF
      - name: Build Flutter Web
        script: |
          flutter build web --release
      - name: Copy manifest to build
        script: |
          cp web/manifest.json build/web/manifest.json
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - mauro.dornik@gmail.com
        notify:
          success: true
          failure: true
