workflows:
  ios-workflow:
    name: iOS DeadTime Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.deadtime.ios
      vars:
        XCODE_WORKSPACE: "ios/DeadTime.xcworkspace"
        XCODE_SCHEME: "DeadTime"
        XCODE_PROJECT: "ios/DeadTime.xcodeproj"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up provisioning profiles
        script: |
          # Set up development provisioning profile
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'" \
            --export-options-plist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
