workflows:
  ios-workflow:
    name: iOS DeadTime Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/DeadTime.xcworkspace"
        XCODE_SCHEME: "DeadTime"
        XCODE_PROJECT: "ios/DeadTime.xcodeproj"
      xcode: latest
    scripts:
      - name: Check iOS project structure
        script: |
          echo "📁 Repository structure:"
          ls -la
          echo "📱 iOS folder contents:"
          ls -la ios/ || echo "❌ iOS folder not found"
          echo "📋 iOS project files:"
          find ios/ -name "*.xcodeproj" -o -name "*.xcworkspace" || echo "❌ No Xcode project found"
      - name: Build iOS app (Direct Xcode)
        script: |
          cd ios
          xcodebuild -project DeadTime.xcodeproj \
            -scheme DeadTime \
            -configuration Debug \
            -destination generic/platform=iOS \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.dSYM
      - /tmp/xcodebuild_logs/*.log
